name: Test suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
  - cron: "0 2 * * 1-5"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Prepare the Rust build environment
      run:
        docker build . --file .github/Dockerfile.ci --tag rust-avr-ci:$GITHUB_RUN_NUMBER

    - name: Compile the crate for the AVR atmega8p
      run:
        docker run rust-avr-ci:$GITHUB_RUN_NUMBER build -Z build-std=core --target avr-atmega8p.json --release --all --bins --examples

    - name: Compile the crate for the host machine and and run tests
      run:
        docker run rust-avr-ci:$GITHUB_RUN_NUMBER test --all
